apiVersion: v1
kind: Pod
metadata:
  name: error-test
spec:
  containers:
    # Example of a commented container
    # - name: nginx
    #   image: ngindfdfadsfsaf
    - name: almalinux
      image: almalinux:9
